### SIGNUP
POST http://localhost:3003/user/signup
Content-Type: application/json

{
    "name": "gatoNegro",
	"email": "gatolNegro@email.com",
	"cpf": "801.560.870-81",
	"password": "abc123"
}

### LOGIN

# @name login

POST http://localhost:3003/user/login 
Content-Type: application/json

{
    "email": "gatolNegro@email.com", 
    "password": "abc123"
}

###

@token = {{login.response.body.token}}

### Profile
GET http://localhost:3003/user/profile
Authorization: {{token}}

### UPDATE PROFILE
PUT http://localhost:3003/user/update
Authorization: {{token}}
Content-Type: application/json

{
    "name": "gatoNegro",
	"email": "gatolNegro@email.com",
	"cpf": "801.560.870-81"
}

### ADD AND CHANGE ADRESS
PUT http://localhost:3003/adress
Authorization: {{token}}
Content-Type: application/json

{
    "street": "R. Afonso Braz",
    "number": "200",
    "neighbourhood": "Vila N. Conceição",
    "city": "São Paulo",
    "state": "SP",
    "complement": "71"
}

### Full adress
GET http://localhost:3003/adress/full
Authorization: {{token}}

### Get Restaurants
GET http://localhost:3003/restaurant/all
Authorization: {{token}}

### add Products
GET http://localhost:3003/restaurant/product
Content-Type: application/json

{   
    "restaurantId": "10",
    "id": "zgKDJFbJDi8YRm4nm9Nj",
    "name": "Sushi shiromi",
    "category": "Refeição",
    "price": 22.8,
    "photoUrl": "https://static-images.ifood.com.br/image/upload/f_auto,t_high/pratos/51fed2ca-70a6-4069-a203-65536c856035/201801251512_20719050.jpg",
    "description": "A melhor pedida é japonesa!"
}

### GET RESTAURANTS PRODUCTS
GET http://localhost:3003/restaurant/detail/2
Authorization: {{token}}

### PLACE ORDER
POST  http://localhost:3003/order/place/2
Authorization: {{token}}
Content-Type: application/json

{
    "products": [{
		"id": "ZtdpRkg7KJ0QoN2TDFaA",
		"quantity": 3
	}, {
		"quantity": 2,
		"id": "QUH0ejMVKcj9N5q7ZLLW"
	}],
	"paymentMethod": "money"
}

### GET ACTIVE ORDER
GET http://localhost:3003/order/active
Authorization: {{token}}

### GET ORDER HISTORY 
GET http://localhost:3003/order/history
Authorization: {{token}}